name = "systemd-cd-frontend"

git_remote_url = "https://github.com/tingtt/systemd-cd-frontend.git"
git_target_branch = "main"
build_commands = ["/root/.local/share/pnpm/pnpm install", "/root/.local/share/pnpm/pnpm build"]

[[systemd_services]]
name = "nextjs-workspace"
description = "tingtt's portfolio with Next.js"
exec_start_pre = "/root/.local/share/pnpm/pnpm install --prod"
exec_start = "/root/.local/share/pnpm/pnpm start"
args = "--port 80"
opt_files = [".next/", "package.json", "public/"]
port = 80