name = "systemd-cd-frontend"

git_remote_url = "https://github.com/tingtt/systemd-cd-frontend.git"
git_target_branch = "main"
build_commands = [
  "/root/.local/share/pnpm/pnpm install",
  """cat << EOF > .env.local
  NEXT_PUBLIC_API_URL=http://192.168.56.4:1323/
  """,
  "/root/.local/share/pnpm/pnpm build",
]

[[systemd_services]]
name = "systemd-cd-frontend"
description = "systemd-cd frontend with Next.js"
exec_start_pre = "/root/.local/share/pnpm/pnpm install --prod"
exec_start = "/root/.local/share/pnpm/pnpm start"
args = "--port 80"
opt_files = [".next/", "package.json", "public/"]
port = 80