name = "systemd-cd-frontend"
git_remote_url = "https://github.com/tingtt/systemd-cd-frontend.git"
git_target_branch = "main"
build_commands = [
  "/usr/local/bin/pnpm install",
  """cat << EOF > .env.local
NEXT_PUBLIC_API_URL=http://localhost:1323/
""",
  "/usr/local/bin/pnpm build",
  "cp -r .next/static .next/standalone/.next/static",
  "cp -r public .next/standalone"
]

[[systemd_services]]
name = "systemd-cd-frontend"
description = "systemd-cd frontend with Next.js"
exec_start = "/usr/bin/node .next/standalone/server.js"
opt_files = [".next/standalone/"]
port = 80

[[systemd_services.env]]
name = "PORT"
value = "80"
