name = "nextjs-workspace"

git_remote_url = "https://github.com/tingtt/workspace-nextjs.git"
git_target_branch = "main"
build_commands = ["/root/.local/share/pnpm/pnpm install", "/root/.local/share/pnpm/pnpm build"]

[[systemd_services]]
name = "nextjs-workspace"
description = "CI/CD sample with Next.js"
exec_start_pre = "/root/.local/share/pnpm/pnpm install next"
exec_start = "/root/.local/share/pnpm/pnpm start"
args = "--port 3000"
opt_files = [".next/", "package.json", "public/"]
port = 3000